networks:
  default:
    external: true
    name: roboshop
services:
  mongodb:
   image: mongodb:1
  catalogue:
   image: catalogue:1
  nginx:
   image: nginx:1
   ports:
   - "80:80"
   depends_on:
   - catalogue
