networks:
  default:
    external: true
    name: roboshop
services:
  mongodb:
   image: mongodb:1
   container_name: mongodb
   volumes:
   - source: mongodb
     target: /data/db
     type: volume

  catalogue:
   image: catalogue:1
   container_name: catalogue

  redis:
   image: redis
   container_name: redis
   volumes:
   - source: mredis
     target: /data
     type: volume

  user:
   image: user:1
   container_name: user
   depends_on:
   - redis
   - mongodb

  cart:
   image: cart:1
   container_name: cart
   depends_on:
   - redis 
   - catalogue

  mysql:
   image: mysql:1
   container_name: mysql
   volumes:
   - source: mysql
     target: /var/lib/mysql
     type: volume

  shipping:
   image: shipping:1
   container_name: shipping
   depends_on:
   - mysql

  rabbitmq:
   image: rabbitmq
   container_name: rabbitmq
   environment:
   - RABBITMQ_DEFAULT_USER=roboshop
   - RABBITMQ_DEFAULT_PASS=roboshop123
   volumes:
    - source: rabbitmq
      target: /var/lib/rabbitmq
      type: volume

  payment:
   container_name: payment
   image: payment:1
   depends_on:
   - rabbitmq
   - user
   - cart
  
  
  web:
   image: web:1
   container_name: web
   ports:
   - "80:80"
   depends_on:
   - catalogue
   - cart
   - user
   - shipping
   - payment
